In [1]:
import numpy as np

# Generate a random 5x2 array of points (values between 0 and 10)
points = np.random.rand(5, 2) * 10
print("2D Points:\n", points)

# Task: Compute pairwise Euclidean distances using broadcasting
# <START: Pairwise distance computation>
distance_matrix = np.linalg.norm(points[:, np.newaxis, :] - points[np.newaxis, :, :], axis=2)
# <END: Pairwise distance computation>

# Print the distance matrix
print("Pairwise Euclidean Distance Matrix:\n", distance_matrix)


2D Points:
 [[4.43152401 2.63056987]
 [4.38673172 2.91239222]
 [3.54068377 1.70466715]
 [8.94031823 6.30843581]
 [7.65125225 6.76991523]]
Pairwise Euclidean Distance Matrix:
 [[0.         0.28535974 1.28487049 5.8185843  5.24412337]
 [0.28535974 0.         1.47458366 5.68051602 5.05347188]
 [1.28487049 1.47458366 0.         7.09582541 6.52330525]
 [5.8185843  5.68051602 7.09582541 0.         1.36918018]
 [5.24412337 5.05347188 6.52330525 1.36918018 0.        ]]
